data=[
    {
        "_id": 21,
        "duration": 992,
        "event": "TED2006",
        "likes": "17K",
        "page_url": "https://www.ted.com/talks/mena_trott_meet_the_founder_of_the_blog_revolution",
        "published_date": "2006-08-25T00:11:00Z",
        "recorded_date": "2006-02-23",
        "related_videos": "[\"144\",\"1282\",\"1379\",\"87\",\"2302\",\"2638\"]",
        "speakers": "[{\"name\":\"Mena Trott\",\"occupation\":\"Blogger; co-founder, Six Apart\"}]",
        "summary": "The founding mother of the blog revolution, Mena Trott, looks back at the changing nature of communication.",
        "title": "Meet the founder of the blog revolution",
        "topics": "[{\"id\":\"4\",\"name\":\"culture\"},{\"id\":\"13\",\"name\":\"internet\"}]",
        "transcript": "Over the past couple of days, as I've been preparing to give my talk, I've been trying to imagine what I would say to all of you...",
        "views": 589115,
        "youtube_video_code": "RlBTxuWCuL8"
    },
    {
        "_id": 1,
        "duration": 957,
        "event": "TED2006",
        "likes": "110K",
        "page_url": "https://www.ted.com/talks/al_gore_averting_the_climate_crisis",
        "published_date": "2006-06-27T00:11:00Z",
        "recorded_date": "2006-02-25",
        "related_videos": "[\"243\",\"547\",\"2093\",\"74405\",\"64693\",\"83767\"]",
        "speakers": "[{\"name\":\"Al Gore\",\"occupation\":\"Climate advocate\"}]",
        "summary": "With the same humor and humanity he exuded in An Inconvenient Truth, Al Gore spells out 15 ways that individuals can address climate change immediately.",
        "title": "Averting the climate crisis",
        "topics": "[{\"id\":\"3\",\"name\":\"climate change\"},{\"id\":\"4\",\"name\":\"environment\"}]",
        "transcript": "Thank you so much, Chris. And it's truly a great honor to have the opportunity to come to this stage again...",
        "views": 3671801,
        "youtube_video_code": "rDiGYuQicpA"
    },
    {
        "_id": 7,
        "duration": 1266,
        "event": "TED2006",
        "likes": "60K",
        "page_url": "https://www.ted.com/talks/david_pogue_simplicity_sells",
        "published_date": "2006-06-27T00:11:00Z",
        "recorded_date": "2006-02-24",
        "related_videos": "[\"1725\",\"2274\",\"172\",\"2664\",\"2464\",\"1268\"]",
        "speakers": "[{\"name\":\"David Pogue\",\"occupation\":\"Technology columnist, The New York Times\"}]",
        "summary": "New York Times columnist David Pogue takes aim at technology's worst interface-design offenders and provides encouraging examples of products that get it right.",
        "title": "Simplicity sells",
        "topics": "[{\"id\":\"10\",\"name\":\"technology\"},{\"id\":\"36\",\"name\":\"design\"}]",
        "transcript": "(Music: \"The Sound of Silence,\" Simon &amp; Garfunkel) (Laughter) Technology is so much fun, but we can drown in our technology...",
        "views": 2008487,
        "youtube_video_code": "NEjZt0y6OOw"
    },
    {
        "_id": 47,
        "duration": 1126,
        "event": "TEDGlobal 2005",
        "likes": "80K",
        "page_url": "https://www.ted.com/talks/david_deutsch_chemical_scum_that_dream_of_distant_quasars",
        "published_date": "2006-09-12T00:11:00Z",
        "recorded_date": "2005-07-14",
        "related_videos": "[\"2237\",\"701\",\"1095\",\"1386\",\"76211\",\"242\"]",
        "speakers": "[{\"name\":\"David Deutsch\",\"occupation\":\"Physicist\"}]",
        "summary": "Legendary scientist David Deutsch puts theoretical physics into context with this gripping talk on the origins and future of the universe.",
        "title": "Chemical scum that dream of distant quasars",
        "topics": "[{\"id\":\"3\",\"name\":\"climate change\"},{\"id\":\"4\",\"name\":\"environment\"}]",
        "transcript": "We've been told to go out on a limb and say something wonderful. My wonderful thing is that we are standing on a huge mental limb...",
        "views": 2694257,
        "youtube_video_code": "gQliI_WGaGk"
    },
    {
        "_id": 55,
        "duration": 1524,
        "event": "TED2006",
        "likes": "14K",
        "page_url": "https://www.ted.com/talks/jehane_noujaim_my_wish_a_global_day_of_film",
        "published_date": "2006-07-25T00:11:00Z",
        "recorded_date": "2006-02-26",
        "related_videos": "[\"2228\",\"1476\",\"800\",\"2890\",\"45233\",\"2694\"]",
        "speakers": "[{\"name\":\"Jehane Noujaim\",\"occupation\":\"Filmmaker\"}]",
        "summary": "Jehane Noujaim unveils her 2006 TED Prize wish: for the world to unite through film. Join Pangea Day to help make the dream come true.",
        "title": "My wish: A global day of film",
        "topics": "[{\"id\":\"4\",\"name\":\"culture\"},{\"id\":\"6\",\"name\":\"entertainment\"}]",
        "transcript": "I can't help but this wish: to think about where we can go when we experience the ideas of others. That was the idea behind this...",
        "views": 489757,
        "youtube_video_code": "QCFSrb6B5nw"
    },
    {
        "_id": 59,
        "duration": 711,
        "event": "TED2006",
        "likes": "22K",
        "page_url": "https://www.ted.com/talks/jonathan_drori_every_pollen_grain_has_a_story",
        "published_date": "2006-08-01T00:11:00Z",
        "recorded_date": "2006-02-23",
        "related_videos": "[\"1984\",\"1452\",\"3272\",\"2740\",\"2614\",\"1349\"]",
        "speakers": "[{\"name\":\"Jonathan Drori\",\"occupation\":\"Director, Culture Online\"}]",
        "summary": "Plants talk to us with color, scent and texture, says Jonathan Drori, and by watching them closely, we can decode nature's messages.",
        "title": "Every pollen grain has a story",
        "topics": "[{\"id\":\"4\",\"name\":\"culture\"},{\"id\":\"13\",\"name\":\"science\"}]",
        "transcript": "I've come to talk to you today about pollen, because pollen can help us in ways that you might not imagine. Pollen gives us clues...",
        "views": 714762,
        "youtube_video_code": "CCNM1XyR7Qc"
    },
    {
        "_id": 73,
        "duration": 1295,
        "event": "TED2006",
        "likes": "14K",
        "page_url": "https://www.ted.com/talks/jane_goodall_what_separates_us_from_the_apes",
        "published_date": "2006-07-20T00:11:00Z",
        "recorded_date": "2006-02-23",
        "related_videos": "[\"415\",\"464\",\"488\",\"251\",\"267\",\"528\"]",
        "speakers": "[{\"name\":\"Jane Goodall\",\"occupation\":\"Primatologist\"}]",
        "summary": "Jane Goodall shares fascinating stories of the chimpanzees she's studied for decades, and offers her thoughts on what differentiates us from our closest relatives.",
        "title": "What separates us from the apes?",
        "topics": "[{\"id\":\"4\",\"name\":\"culture\"},{\"id\":\"9\",\"name\":\"humanity\"}]",
        "transcript": "As I was walking through the forest in Gombe National Park, a group of chimpanzees approached me. I was about to see something...",
        "views": 999536,
        "youtube_video_code": "AX2F5pNTFz0"
    },
        {
            "_id": 104,
            "duration": 1089,
            "event": "TED2006",
            "likes": "11K",
            "page_url": "https://www.ted.com/talks/jane_goodall_conservation_and_hope",
            "published_date": "2006-08-02T00:11:00Z",
            "recorded_date": "2006-03-04",
            "related_videos": "[\"432\",\"352\",\"142\",\"542\",\"231\",\"432\"]",
            "speakers": "[{\"name\":\"Jane Goodall\",\"occupation\":\"Primatologist\"}]",
            "summary": "Jane Goodall talks about conservation efforts and the hope for a better future for our planet.",
            "title": "Conservation and hope",
            "topics": "[{\"id\":\"4\",\"name\":\"culture\"},{\"id\":\"9\",\"name\":\"humanity\"}]",
            "transcript": "I am here today to talk about conservation efforts and the hope that we can create a better future for our planet...",
            "views": 456731,
            "youtube_video_code": "yY1NuZ1e1Oo"
        },
        {
            "_id": 105,
            "duration": 1015,
            "event": "TED2006",
            "likes": "9K",
            "page_url": "https://www.ted.com/talks/jane_goodall_chimpanzees_and_us",
            "published_date": "2006-08-03T00:11:00Z",
            "recorded_date": "2006-03-05",
            "related_videos": "[\"432\",\"352\",\"142\",\"542\",\"231\",\"432\"]",
            "speakers": "[{\"name\":\"Jane Goodall\",\"occupation\":\"Primatologist\"}]",
            "summary": "Jane Goodall shares insights on the similarities between chimpanzees and humans, based on her extensive research.",
            "title": "Chimpanzees and us",
            "topics": "[{\"id\":\"4\",\"name\":\"culture\"},{\"id\":\"9\",\"name\":\"humanity\"}]",
            "transcript": "I am here today to share insights on the similarities between chimpanzees and humans. Through my research, I have learned...",
            "views": 456731,
            "youtube_video_code": "yY2NuZ2e2Oo"
        },
        {
            "_id": 106,
            "duration": 1020,
            "event": "TED2006",
            "likes": "13K",
            "page_url": "https://www.ted.com/talks/jane_goodall_on_nature_and_technology",
            "published_date": "2006-08-04T00:11:00Z",
            "recorded_date": "2006-03-06",
            "related_videos": "[\"432\",\"352\",\"142\",\"542\",\"231\",\"432\"]",
            "speakers": "[{\"name\":\"Jane Goodall\",\"occupation\":\"Primatologist\"}]",
            "summary": "Jane Goodall discusses the relationship between nature and technology and how they can coexist.",
            "title": "On nature and technology",
            "topics": "[{\"id\":\"4\",\"name\":\"culture\"},{\"id\":\"9\",\"name\":\"humanity\"}]",
            "transcript": "I am here today to talk about the relationship between nature and technology. We must find ways for them to coexist...",
            "views": 479731,
            "youtube_video_code": "yY3NuZ3e3Oo"
        },
        {
            "_id": 107,
            "duration": 987,
            "event": "TED2006",
            "likes": "10K",
            "page_url": "https://www.ted.com/talks/jane_goodall_inspiring_the_next_generation",
            "published_date": "2006-08-05T00:11:00Z",
            "recorded_date": "2006-03-07",
            "related_videos": "[\"432\",\"352\",\"142\",\"542\",\"231\",\"432\"]",
            "speakers": "[{\"name\":\"Jane Goodall\",\"occupation\":\"Primatologist\"}]",
            "summary": "Jane Goodall inspires the next generation to take action for the environment and make a difference.",
            "title": "Inspiring the next generation",
            "topics": "[{\"id\":\"4\",\"name\":\"culture\"},{\"id\":\"9\",\"name\":\"humanity\"}]",
            "transcript": "I am here today to inspire the next generation to take action for the environment. Each of us has the power to make a difference...",
            "views": 456731,
            "youtube_video_code": "yY4NuZ4e4Oo"
        },
        {
            "_id": 108,
            "duration": 1035,
            "event": "TED2006",
            "likes": "12K",
            "page_url": "https://www.ted.com/talks/jane_goodall_wisdom_from_the_wild",
            "published_date": "2006-08-06T00:11:00Z",
            "recorded_date": "2006-03-08",
            "related_videos": "[\"432\",\"352\",\"142\",\"542\",\"231\",\"432\"]",
            "speakers": "[{\"name\":\"Jane Goodall\",\"occupation\":\"Primatologist\"}]",
            "summary": "Jane Goodall shares wisdom from the wild and what we can learn from the animal kingdom.",
            "title": "Wisdom from the wild",
            "topics": "[{\"id\":\"4\",\"name\":\"culture\"},{\"id\":\"9\",\"name\":\"humanity\"}]",
            "transcript": "I am here today to share wisdom from the wild. The animal kingdom has much to teach us about living in harmony with nature...",
            "views": 456731,
            "youtube_video_code": "yY5NuZ5e5Oo"
        },
        {
            "_id": 109,
            "duration": 1112,
            "event": "TED2006",
            "likes": "11K",
            "page_url": "https://www.ted.com/talks/jane_goodall_a_lifetime_of_learning",
            "published_date": "2006-08-07T00:11:00Z",
            "recorded_date": "2006-03-09",
            "related_videos": "[\"432\",\"352\",\"142\",\"542\",\"231\",\"432\"]",
            "speakers": "[{\"name\":\"Jane Goodall\",\"occupation\":\"Primatologist\"}]",
            "summary": "Jane Goodall reflects on her lifetime of learning from chimpanzees and the lessons they have taught her.",
            "title": "A lifetime of learning",
            "topics": "[{\"id\":\"4\",\"name\":\"culture\"},{\"id\":\"9\",\"name\":\"humanity\"}]",
            "transcript": "I am here today to reflect on my lifetime of learning from chimpanzees. These incredible creatures have taught me so much...",
            "views": 456731,
            "youtube_video_code": "yY6NuZ6e6Oo"
        },
        {
            "_id": 110,
            "duration": 1024,
            "event": "TED2006",
            "likes": "13K",
            "page_url": "https://www.ted.com/talks/jane_goodall_the_future_of_chimpanzees",
            "published_date": "2006-08-08T00:11:00Z",
            "recorded_date": "2006-03-10",
            "related_videos": "[\"432\",\"352\",\"142\",\"542\",\"231\",\"432\"]",
            "speakers": "[{\"name\":\"Jane Goodall\",\"occupation\":\"Primatologist\"}]",
            "summary": "Jane Goodall discusses the future of chimpanzees and the conservation efforts needed to protect them.",
            "title": "The future of chimpanzees",
            "topics": "[{\"id\":\"4\",\"name\":\"culture\"},{\"id\":\"9\",\"name\":\"humanity\"}]",
            "transcript": "I am here today to talk about the future of chimpanzees. These remarkable animals are facing many threats...",
            "views": 456731,
            "youtube_video_code": "yY7NuZ7e7Oo"
        },
        {
            "_id": 111,
            "duration": 1103,
            "event": "TED2006",
            "likes": "14K",
            "page_url": "https://www.ted.com/talks/jane_goodall_my_journey_with_chimpanzees",
            "published_date": "2006-08-09T00:11:00Z",
            "recorded_date": "2006-03-11",
            "related_videos": "[\"432\",\"352\",\"142\",\"542\",\"231\",\"432\"]",
            "speakers": "[{\"name\":\"Jane Goodall\",\"occupation\":\"Primatologist\"}]",
            "summary": "Jane Goodall shares her personal journey with chimpanzees and the profound impact they have had on her life.",
            "title": "My journey with chimpanzees",
            "topics": "[{\"id\":\"4\",\"name\":\"culture\"},{\"id\":\"9\",\"name\":\"humanity\"}]",
            "transcript": "I am here today to share my personal journey with chimpanzees. These amazing creatures have had a profound impact on my life...",
            "views": 456731,
            "youtube_video_code": "yY8NuZ8e8Oo"
        },
        {
            "_id": 112,
            "duration": 1001,
            "event": "TED2006",
            "likes": "15K",
            "page_url": "https://www.ted.com/talks/jane_goodall_the_inspiration_of_youth",
            "published_date": "2006-08-10T00:11:00Z",
            "recorded_date": "2006-03-12",
            "related_videos": "[\"432\",\"352\",\"142\",\"542\",\"231\",\"432\"]",
            "speakers": "[{\"name\":\"Jane Goodall\",\"occupation\":\"Primatologist\"}]",
            "summary": "Jane Goodall discusses the inspiration she draws from young people and their potential to create change.",
            "title": "The inspiration of youth",
            "topics": "[{\"id\":\"4\",\"name\":\"culture\"},{\"id\":\"9\",\"name\":\"humanity\"}]",
            "transcript": "I am here today to talk about the inspiration I draw from young people. They have the potential to create real change...",
            "views": 456731,
            "youtube_video_code": "yY9NuZ9e9Oo"
        },
        {
            "_id": 113,
            "duration": 1098,
            "event": "TED2006",
            "likes": "16K",
            "page_url": "https://www.ted.com/talks/jane_goodall_the_future_of_our_planet",
            "published_date": "2006-08-11T00:11:00Z",
            "recorded_date": "2006-03-13",
            "related_videos": "[\"432\",\"352\",\"142\",\"542\",\"231\",\"432\"]",
            "speakers": "[{\"name\":\"Jane Goodall\",\"occupation\":\"Primatologist\"}]",
            "summary": "Jane Goodall speaks about the future of our planet and the urgent need for conservation and sustainable practices.",
            "title": "The future of our planet",
            "topics": "[{\"id\":\"4\",\"name\":\"culture\"},{\"id\":\"9\",\"name\":\"humanity\"}]",
            "transcript": "I am here today to discuss the future of our planet. There is an urgent need for conservation and sustainable practices...",
            "views": 456731,
            "youtube_video_code": "yY0NuZ0e0Oo"
        },
        {
            "_id": 114,
            "duration": 1034,
            "event": "TED2006",
            "likes": "17K",
            "page_url": "https://www.ted.com/talks/jane_goodall_animal_empathy",
            "published_date": "2006-08-12T00:11:00Z",
            "recorded_date": "2006-03-14",
            "related_videos": "[\"432\",\"352\",\"142\",\"542\",\"231\",\"432\"]",
            "speakers": "[{\"name\":\"Jane Goodall\",\"occupation\":\"Primatologist\"}]",
            "summary": "Jane Goodall explores the concept of animal empathy and what humans can learn from it.",
            "title": "Animal empathy",
            "topics": "[{\"id\":\"4\",\"name\":\"culture\"},{\"id\":\"9\",\"name\":\"humanity\"}]",
            "transcript": "I am here today to explore the concept of animal empathy. These incredible creatures can teach us so much about empathy...",
            "views": 456731,
            "youtube_video_code": "yY1NuZ1e1Oo"
        },
        {
            "_id": 115,
            "duration": 1095,
            "event": "TED2006",
            "likes": "18K",
            "page_url": "https://www.ted.com/talks/jane_goodall_the_human_connection_to_animals",
            "published_date": "2006-08-13T00:11:00Z",
            "recorded_date": "2006-03-15",
            "related_videos": "[\"432\",\"352\",\"142\",\"542\",\"231\",\"432\"]",
            "speakers": "[{\"name\":\"Jane Goodall\",\"occupation\":\"Primatologist\"}]",
            "summary": "Jane Goodall discusses the deep connection between humans and animals and the importance of this relationship.",
            "title": "The human connection to animals",
            "topics": "[{\"id\":\"4\",\"name\":\"culture\"},{\"id\":\"9\",\"name\":\"humanity\"}]",
            "transcript": "I am here today to discuss the deep connection between humans and animals. This relationship is so important...",
            "views": 456731,
            "youtube_video_code": "yY2NuZ2e2Oo"
        },
        {
            "_id": 116,
            "duration": 1068,
            "event": "TED2006",
            "likes": "19K",
            "page_url": "https://www.ted.com/talks/jane_goodall_leadership_lessons_from_the_animal_kingdom",
            "published_date": "2006-08-14T00:11:00Z",
            "recorded_date": "2006-03-16",
            "related_videos": "[\"432\",\"352\",\"142\",\"542\",\"231\",\"432\"]",
            "speakers": "[{\"name\":\"Jane Goodall\",\"occupation\":\"Primatologist\"}]",
            "summary": "Jane Goodall shares leadership lessons she has learned from studying animals in the wild.",
            "title": "Leadership lessons from the animal kingdom",
            "topics": "[{\"id\":\"4\",\"name\":\"culture\"},{\"id\":\"9\",\"name\":\"humanity\"}]",
            "transcript": "I am here today to share leadership lessons I have learned from studying animals in the wild. These lessons are invaluable...",
            "views": 456731,
            "youtube_video_code": "yY3NuZ3e3Oo"
        },
        {
            "_id": 117,
            "duration": 1076,
            "event": "TED2006",
            "likes": "20K",
            "page_url": "https://www.ted.com/talks/jane_goodall_a_lifetime_of_conservation",
            "published_date": "2006-08-15T00:11:00Z",
            "recorded_date": "2006-03-17",
            "related_videos": "[\"432\",\"352\",\"142\",\"542\",\"231\",\"432\"]",
            "speakers": "[{\"name\":\"Jane Goodall\",\"occupation\":\"Primatologist\"}]",
            "summary": "Jane Goodall reflects on her lifetime of conservation work and the importance of protecting the environment.",
            "title": "A lifetime of conservation",
            "topics": "[{\"id\":\"4\",\"name\":\"culture\"},{\"id\":\"9\",\"name\":\"humanity\"}]",
            "transcript": "I am here today to reflect on my lifetime of conservation work. Protecting the environment is more important now than ever...",
            "views": 456731,
            "youtube_video_code": "yY4NuZ4e4Oo"
        },
        [
            {
                "_id": 118,
                "duration": 1111,
                "event": "TED2006",
                "likes": "21K",
                "page_url": "https://www.ted.com/talks/jane_goodall_the_power_of_hope",
                "published_date": "2006-08-16T00:11:00Z",
                "recorded_date": "2006-03-18",
                "related_videos": "[\"432\",\"352\",\"142\",\"542\",\"231\",\"432\"]",
                "speakers": "[{\"name\":\"Jane Goodall\",\"occupation\":\"Primatologist\"}]",
                "summary": "Jane Goodall talks about the power of hope and its role in driving positive change.",
                "title": "The power of hope",
                "topics": "[{\"id\":\"4\",\"name\":\"culture\"},{\"id\":\"9\",\"name\":\"humanity\"}]",
                "transcript": "I am here today to talk about the power of hope. Hope is a driving force that can lead to positive change...",
                "views": 456731,
                "youtube_video_code": "yY5NuZ5e5Oo"
            },
            {
                "_id": 119,
                "duration": 1045,
                "event": "TED2006",
                "likes": "22K",
                "page_url": "https://www.ted.com/talks/jane_goodall_protecting_our_shared_home",
                "published_date": "2006-08-17T00:11:00Z",
                "recorded_date": "2006-03-19",
                "related_videos": "[\"432\",\"352\",\"142\",\"542\",\"231\",\"432\"]",
                "speakers": "[{\"name\":\"Jane Goodall\",\"occupation\":\"Primatologist\"}]",
                "summary": "Jane Goodall emphasizes the importance of protecting our shared home, the Earth, for future generations.",
                "title": "Protecting our shared home",
                "topics": "[{\"id\":\"4\",\"name\":\"culture\"},{\"id\":\"9\",\"name\":\"humanity\"}]",
                "transcript": "I am here today to emphasize the importance of protecting our shared home, the Earth. It is our responsibility to ensure a livable future...",
                "views": 456731,
                "youtube_video_code": "yY6NuZ6e6Oo"
            },
            {
                "_id": 120,
                "duration": 1100,
                "event": "TED2006",
                "likes": "23K",
                "page_url": "https://www.ted.com/talks/jane_goodall_respecting_all_living_beings",
                "published_date": "2006-08-18T00:11:00Z",
                "recorded_date": "2006-03-20",
                "related_videos": "[\"432\",\"352\",\"142\",\"542\",\"231\",\"432\"]",
                "speakers": "[{\"name\":\"Jane Goodall\",\"occupation\":\"Primatologist\"}]",
                "summary": "Jane Goodall talks about the importance of respecting all living beings and the interconnectedness of life.",
                "title": "Respecting all living beings",
                "topics": "[{\"id\":\"4\",\"name\":\"culture\"},{\"id\":\"9\",\"name\":\"humanity\"}]",
                "transcript": "I am here today to talk about the importance of respecting all living beings. All life is interconnected...",
                "views": 456731,
                "youtube_video_code": "yY7NuZ7e7Oo"
            },
            {
                "_id": 121,
                "duration": 1058,
                "event": "TED2006",
                "likes": "24K",
                "page_url": "https://www.ted.com/talks/jane_goodall_the_wisdom_of_nature",
                "published_date": "2006-08-19T00:11:00Z",
                "recorded_date": "2006-03-21",
                "related_videos": "[\"432\",\"352\",\"142\",\"542\",\"231\",\"432\"]",
                "speakers": "[{\"name\":\"Jane Goodall\",\"occupation\":\"Primatologist\"}]",
                "summary": "Jane Goodall shares the wisdom of nature and what humans can learn from the natural world.",
                "title": "The wisdom of nature",
                "topics": "[{\"id\":\"4\",\"name\":\"culture\"},{\"id\":\"9\",\"name\":\"humanity\"}]",
                "transcript": "I am here today to share the wisdom of nature. There is so much we can learn from the natural world...",
                "views": 456731,
                "youtube_video_code": "yY8NuZ8e8Oo"
            },
            {
                "_id": 122,
                "duration": 1120,
                "event": "TED2006",
                "likes": "25K",
                "page_url": "https://www.ted.com/talks/jane_goodall_harmony_with_nature",
                "published_date": "2006-08-20T00:11:00Z",
                "recorded_date": "2006-03-22",
                "related_videos": "[\"432\",\"352\",\"142\",\"542\",\"231\",\"432\"]",
                "speakers": "[{\"name\":\"Jane Goodall\",\"occupation\":\"Primatologist\"}]",
                "summary": "Jane Goodall discusses the concept of living in harmony with nature and its benefits for both humans and the environment.",
                "title": "Harmony with nature",
                "topics": "[{\"id\":\"4\",\"name\":\"culture\"},{\"id\":\"9\",\"name\":\"humanity\"}]",
                "transcript": "I am here today to discuss the concept of living in harmony with nature. This approach benefits both humans and the environment...",
                "views": 456731,
                "youtube_video_code": "yY9NuZ9e9Oo"
            },
            {
                "_id": 123,
                "duration": 1067,
                "event": "TED2006",
                "likes": "26K",
                "page_url": "https://www.ted.com/talks/jane_goodall_building_a_better_world",
                "published_date": "2006-08-21T00:11:00Z",
                "recorded_date": "2006-03-23",
                "related_videos": "[\"432\",\"352\",\"142\",\"542\",\"231\",\"432\"]",
                "speakers": "[{\"name\":\"Jane Goodall\",\"occupation\":\"Primatologist\"}]",
                "summary": "Jane Goodall speaks about building a better world through environmental conservation and community engagement.",
                "title": "Building a better world",
                "topics": "[{\"id\":\"4\",\"name\":\"culture\"},{\"id\":\"9\",\"name\":\"humanity\"}]",
                "transcript": "I am here today to speak about building a better world. Environmental conservation and community engagement are key...",
                "views": 456731,
                "youtube_video_code": "yY0NuZ0e0Oo"
            },
            {
                "_id": 124,
                "duration": 1099,
                "event": "TED2006",
                "likes": "27K",
                "page_url": "https://www.ted.com/talks/jane_goodall_the_next_generation_of_conservationists",
                "published_date": "2006-08-22T00:11:00Z",
                "recorded_date": "2006-03-24",
                "related_videos": "[\"432\",\"352\",\"142\",\"542\",\"231\",\"432\"]",
                "speakers": "[{\"name\":\"Jane Goodall\",\"occupation\":\"Primatologist\"}]",
                "summary": "Jane Goodall highlights the next generation of conservationists and their role in shaping the future.",
                "title": "The next generation of conservationists",
                "topics": "[{\"id\":\"4\",\"name\":\"culture\"},{\"id\":\"9\",\"name\":\"humanity\"}]",
                "transcript": "I am here today to highlight the next generation of conservationists. Their role in shaping the future is crucial...",
                "views": 456731,
                "youtube_video_code": "yY1NuZ1e1Oo"
            },
            {
                "_id": 125,
                "duration": 1112,
                "event": "TED2006",
                "likes": "28K",
                "page_url": "https://www.ted.com/talks/jane_goodall_the_importance_of_community",
                "published_date": "2006-08-23T00:11:00Z",
                "recorded_date": "2006-03-25",
                "related_videos": "[\"432\",\"352\",\"142\",\"542\",\"231\",\"432\"]",
                "speakers": "[{\"name\":\"Jane Goodall\",\"occupation\":\"Primatologist\"}]",
                "summary": "Jane Goodall speaks about the importance of community in conservation efforts and social change.",
                "title": "The importance of community",
                "topics": "[{\"id\":\"4\",\"name\":\"culture\"},{\"id\":\"9\",\"name\":\"humanity\"}]",
                "transcript": "I am here today to speak about the importance of community in conservation efforts and social change...",
                "views": 456731,
                "youtube_video_code": "yY2NuZ2e2Oo"
            },
            {
                "_id": 126,
                "duration": 1083,
                "event": "TED2006",
                "likes": "29K",
                "page_url": "https://www.ted.com/talks/jane_goodall_reconnecting_with_nature",
                "published_date": "2006-08-24T00:11:00Z",
                "recorded_date": "2006-03-26",
                "related_videos": "[\"432\",\"352\",\"142\",\"542\",\"231\",\"432\"]",
                "speakers": "[{\"name\":\"Jane Goodall\",\"occupation\":\"Primatologist\"}]",
                "summary": "Jane Goodall discusses the need for humans to reconnect with nature and the benefits of doing so.",
                "title": "Reconnecting with nature",
                "topics": "[{\"id\":\"4\",\"name\":\"culture\"},{\"id\":\"9\",\"name\":\"humanity\"}]",
                "transcript": "I am here today to discuss the need for humans to reconnect with nature. The benefits of doing so are immense...",
                "views": 456731,
                "youtube_video_code": "yY3NuZ3e3Oo"
            },
            {
                "_id": 127,
                "duration": 1094,
                "event": "TED2006",
                "likes": "30K",
                "page_url": "https://www.ted.com/talks/jane_goodall_the_spirit_of_hope",
                "published_date": "2006-08-25T00:11:00Z",
                "recorded_date": "2006-03-27",
                "related_videos": "[\"432\",\"352\",\"142\",\"542\",\"231\",\"432\"]",
                "speakers": "[{\"name\":\"Jane Goodall\",\"occupation\":\"Primatologist\"}]",
                "summary": "Jane Goodall talks about the spirit of hope and its power to drive positive change in the world.",
                "title": "The spirit of hope",
                "topics": "[{\"id\":\"4\",\"name\":\"culture\"},{\"id\":\"9\",\"name\":\"humanity\"}]",
                "transcript": "I am here today to talk about the spirit of hope. Hope has the power to drive positive change in the world...",
                "views": 456731,
                "youtube_video_code": "yY4NuZ4e4Oo"
            },
            {
                "_id": 128,
                "duration": 1107,
                "event": "TED2006",
                "likes": "31K",
                "page_url": "https://www.ted.com/talks/jane_goodall_living_with_purpose",
                "published_date": "2006-08-26T00:11:00Z",
                "recorded_date": "2006-03-28",
                "related_videos": "[\"432\",\"352\",\"142\",\"542\",\"231\",\"432\"]",
                "speakers": "[{\"name\":\"Jane Goodall\",\"occupation\":\"Primatologist\"}]",
                "summary": "Jane Goodall discusses the importance of living with purpose and how it can lead to a fulfilling life.",
                "title": "Living with purpose",
                "topics": "[{\"id\":\"4\",\"name\":\"culture\"},{\"id\":\"9\",\"name\":\"humanity\"}]",
                "transcript": "I am here today to discuss the importance of living with purpose. A purposeful life can be truly fulfilling...",
                "views": 456731,
                "youtube_video_code": "yY5NuZ5e5Oo"
            },
            {
                "_id": 129,
                "duration": 1089,
                "event": "TED2006",
                "likes": "32K",
                "page_url": "https://www.ted.com/talks/jane_goodall_the_future_of_conservation",
                "published_date": "2006-08-27T00:11:00Z",
                "recorded_date": "2006-03-29",
                "related_videos": "[\"432\",\"352\",\"142\",\"542\",\"231\",\"432\"]",
                "speakers": "[{\"name\":\"Jane Goodall\",\"occupation\":\"Primatologist\"}]",
                "summary": "Jane Goodall talks about the future of conservation and the role of innovative approaches in protecting the planet.",
                "title": "The future of conservation",
                "topics": "[{\"id\":\"4\",\"name\":\"culture\"},{\"id\":\"9\",\"name\":\"humanity\"}]",
                "transcript": "I am here today to talk about the future of conservation. Innovative approaches are crucial in protecting our planet...",
                "views": 456731,
                "youtube_video_code": "yY6NuZ6e6Oo"
            },
            {
                "_id": 130,
                "duration": 1116,
                "event": "TED2006",
                "likes": "33K",
                "page_url": "https://www.ted.com/talks/jane_goodall_wisdom_from_the_wild",
                "published_date": "2006-08-28T00:11:00Z",
                "recorded_date": "2006-03-30",
                "related_videos": "[\"432\",\"352\",\"142\",\"542\",\"231\",\"432\"]",
                "speakers": "[{\"name\":\"Jane Goodall\",\"occupation\":\"Primatologist\"}]",
                "summary": "Jane Goodall shares wisdom gained from her experiences in the wild and how it applies to modern life.",
                "title": "Wisdom from the wild",
                "topics": "[{\"id\":\"4\",\"name\":\"culture\"},{\"id\":\"9\",\"name\":\"humanity\"}]",
                "transcript": "I am here today to share wisdom gained from my experiences in the wild. These lessons apply to modern life in many ways...",
                "views": 456731,
                "youtube_video_code": "yY7NuZ7e7Oo"
            },
            {
                "_id": 131,
                "duration": 1123,
                "event": "TED2006",
                "likes": "34K",
                "page_url": "https://www.ted.com/talks/jane_goodall_creating_a_sustainable_future",
                "published_date": "2006-08-29T00:11:00Z",
                "recorded_date": "2006-03-31",
                "related_videos": "[\"432\",\"352\",\"142\",\"542\",\"231\",\"432\"]",
                "speakers": "[{\"name\":\"Jane Goodall\",\"occupation\":\"Primatologist\"}]",
                "summary": "Jane Goodall talks about the need for creating a sustainable future and the steps required to achieve it.",
                "title": "Creating a sustainable future",
                "topics": "[{\"id\":\"4\",\"name\":\"culture\"},{\"id\":\"9\",\"name\":\"humanity\"}]",
                "transcript": "I am here today to talk about the need for creating a sustainable future. The steps required to achieve this are crucial...",
                "views": 456731,
                "youtube_video_code": "yY8NuZ8e8Oo"
            },
            
            
        ]
        

    ]
   export default data;

        